services:
  coffee:
    build:
      context: .
    tty: true
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - coffee-data:/usr/src/app/src/data

volumes:
  coffee-data:
